In [3]:
import numpy as np

In [4]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
[3.14, 4, 2, 3]

[3.14, 4, 2, 3]

In [6]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [7]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [8]:
a1 = np.array([1, 2, 3, 4])

In [9]:
type(a1)

numpy.ndarray

In [11]:
a2 = np.array([[1,2,3],
               [4,5,6]])

In [12]:
type(a2)

numpy.ndarray

In [13]:
a2.shape

(2, 3)

In [14]:
a2.ndim

2

In [16]:
a2.size

6

# Creating Numpy Arrays from Scratch

## zeros, ones, full, arange, linspace

In [20]:
np.zeros([2,4], dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [22]:
np.ones([2,4], dtype = float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
# Create an array filled with a linear sepence
# Starting at 0, ending at 20, stepping by 20
# (this is similar to the built-in range() function)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
np.full((2,3), 6.9)

array([[6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9]])

In [26]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## random

In [31]:
# Seed for reproducibility
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [34]:
np.random.rand(4,4)

array([[0.3595079 , 0.43703195, 0.6976312 , 0.06022547],
       [0.66676672, 0.67063787, 0.21038256, 0.1289263 ],
       [0.31542835, 0.36371077, 0.57019677, 0.43860151],
       [0.98837384, 0.10204481, 0.20887676, 0.16130952]])

In [32]:
np.random.normal(0,1,(3,3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [33]:
np.random.randint(1,999, (4,4))

array([[184,  29, 803, 129],
       [129, 933,  54, 902],
       [551, 489, 757, 274],
       [336, 389, 618,  43]])

## Array Indexing & Slicing
### One-dimensional subarray

In [35]:
x1 = np.random.randint(20, size = 6)

In [36]:
x1

array([ 4,  8, 14, 15,  3, 15])

In [37]:
x1[4], x1[0], x1[-1]

(3, 4, 15)

### Multi-dimensional array

In [38]:
x2 = np.random.randint(10, size = (3,4))

In [39]:
x2

array([[5, 5, 0, 1],
       [5, 9, 3, 0],
       [5, 0, 1, 2]])

x2[1,2] = 6

In [42]:
x2

array([[5, 5, 0, 1],
       [5, 9, 6, 0],
       [5, 0, 1, 2]])

### Slicing

In [43]:
x1

array([ 4,  8, 14, 15,  3, 15])

In [46]:
x1[2:4]

array([ 4, 14,  3])

In [47]:
x1[::2]

array([ 4, 14,  3])

In [48]:
x2

array([[5, 5, 0, 1],
       [5, 9, 6, 0],
       [5, 0, 1, 2]])

In [49]:
x2[0:2,0:2]

array([[5, 5],
       [5, 9]])

### Reshaping of Arrays & Transpose

In [52]:
grid = np.arange(1,10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
x = np.array([1,2,3])

In [55]:
x

array([1, 2, 3])

In [56]:
x.reshape((1,3))

array([[1, 2, 3]])

In [57]:
x = np.array([[1.,2.],[3.,4.]])

In [58]:
x

array([[1., 2.],
       [3., 4.]])

In [59]:
x.T

array([[1., 3.],
       [2., 4.]])

### Array Concatenation and Splitting

In [62]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [65]:
grid = np.array([[1,2,3],
                 [4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
np.concatenate((grid, grid))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [69]:
np.concatenate((grid, grid), axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
#vstack
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                []])